language: ruby
sudo: false
cache: bundler
# Latest stable versions of Ruby (as of 2020-08-07) compatible with Vagrant
# v2.2.9.
rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
# See https://docs.travis-ci.com/user/languages/ruby/#bundler-20
before_install:
  - yes | gem update --system --force
  - gem install bundler
script: bundle exec rake
